sudo: false
dist: focal
language: minimal
cache:
  apt: true
env:
  global:
  - SPHINXBUILD=~/.local/bin/sphinx-build
git:
  depth: false
addons:
  apt:
    packages:
    - python3-sphinx
    - python3-pip
    - latexmk
    - libalgorithm-diff-perl
    - texlive
    - texlive-latex-extra
    - texlive-humanities
    - libalgorithm-diff-perl
script:
- make all

before_deploy:
- cp build/latex/ebbr.pdf build/ebbr-$TRAVIS_TAG.pdf

# this works for the offical repo and should work for anyone's fork
# opt in by defining GITHUB_TOKEN
# you can test with random tags but they should not flow back to the official
# repo
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - build/ebbr-*.pdf
  skip_cleanup: true
  on:
    tags: true
    condition: -n "$GITHUB_TOKEN"

# random user fork, pushes to any branch will deploy to that repo's pages
# you must enable github pages for your account and for this repo's fork
# you must opt in to this by defining GITHUB_TOKEN
# (This prevents errors if user does not setup github pages.)
# The repos website will have the pages from whichever branch pushed last
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/all
  skip_cleanup: true
  on:
    all_branches: true
    repo: NOT IN (arm-software/ebbr, wmamills/ebbr)
    condition: -n "$GITHUB_TOKEN"

# Special rule for bill while he tests both github actions and travis
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/all
  skip_cleanup: true
  on:
    branch: tmp-travis
    repo:  wmamills/ebbr

# official repo
# only deploy singlehtml and only on push to main
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/singlehtml
  skip_cleanup: true
  on:
    repo: arm-software/ebbr
    branch: main
