sudo: false
dist: focal
language: minimal
cache:
  apt: true
env:
  global:
  - SPHINXBUILD=~/.local/bin/sphinx-build
git:
  depth: false
addons:
  apt:
    packages:
    - python3-sphinx
    - python3-pip
    - latexmk
    - libalgorithm-diff-perl
    - texlive
    - texlive-latex-extra
    - texlive-humanities
    - libalgorithm-diff-perl
script:
- make all
before_deploy:
- cp build/latex/ebbr.pdf build/ebbr-$TRAVIS_TAG.pdf
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - build/ebbr-*.pdf
  skip_cleanup: true
  on:
    tags: true
    condition: -n "$GITHUB_TOKEN"
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/all
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_REPO != "arm-software/ebbr"
    condition: -n "$GITHUB_TOKEN"
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/singlehtml
  skip_cleanup: true
  on:
    repo: arm-software/ebbr
    branch: main
