sudo: false
dist: focal
cache:
  apt: true
env:
  global:
  - SPHINXBUILD=~/.local/bin/sphinx-build
git:
  depth: false
addons:
  apt:
    packages:
    - python3-pip
    - latexmk
    - libalgorithm-diff-perl
    - texlive
    - texlive-latex-extra
    - texlive-humanities
script:
- make latexpdf
- make html
- make singlehtml
before_deploy:
- cp build/latex/ebbr.pdf build/ebbr-$TRAVIS_TAG.pdf
deploy:
- provider: releases
  prerelease: true
  file_glob: true
  file:
  - build/ebbr-*.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: tmp-build
    repo: wmamills/ebbr
- provider: pages
  github_token: "$GITHUB_TOKEN"
  local_dir: build/singlehtml
  skip_cleanup: true
  on:
    branch: tmp_build
