name: main-ci

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:

    pull_request:

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build-and-deploy:
        # The type of runner that the job will run on
        runs-on: ubuntu-20.04

        steps:
            # Check out this repo w/ all history and tags
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: project sudo level setup
              run: sudo ./scripts/setup.sh admin_setup

            - name: project user level setuo
              run: ./scripts/setup.sh prj_setup

            - name: git describe
              run: git describe

            - name: make html
              run: make html

            - name: make singlehtml
              run: make html

            - name: make pdf
              run: make latexpdf

            # "all" would be enough but this puts each sub-build into its own
            # github action step so it is easy to expand/colapse the logs
            - name: make all
              run: make all

            - name: Deploy to gh_pages
              uses: JamesIves/github-pages-deploy-action@4.1.3
              with:
                branch: gh-pages
                folder: build/all
